### PR TITLE
Initial Interfaces

### PR DESCRIPTION
**Pull request by XedinUnknown**

### CODE REVIEW

**Review by mecha — APPROVED** [review]
Somewhat uncomfortable with myself for saying this; but it looks good. Can't find anything wrong with it.

I do have a question however. Would a `WalkerInterface` or `WalkCapableInterface` be useful? It would declare a `walk(IteratorInterface $iterator)` method. Thoughts?

**Comment by XedinUnknown** [comment]
@mecha, I understand your discomfort. How often is there a PR that has absolutely nothing wrong with it? :D

About the walker, this all started by me wanting to write a class/trait that would walk a hierarchical structure recursively. One thing lead to another, and I concluded that the best solution is the `RecursiveIteratorInterface`, which basically visits every node (walks the tree) while providing a way to re-construct the hierarchy. IMHO, it is sufficient already.

**Comment by mecha** [comment]
Right. This of course implies that the iterator implementation must have at least some internal means to retrieving, and consequently checking if there are, children. Which is precisely what we want.

👍

**Review by mecha — APPROVED** [review]

**Comment by XedinUnknown** [comment]
So, I need something that will guarantee the return of `IterationInterface`, primarily for exceptions which I am now adding. And `getCurrent()` is too generic. If I create another interface, then the method won't be `getCurrent()` any more. So, I'm thinking to leave the declaration of `getCurrent(): mixed` to another package, and change the one in this package to `CurrentAwareInterface#getCurrent(): IterationInterface`. @mecha, thoughts?

**Comment by mecha** [comment]
@XedinUnknown Agreed.

But I have to question the naming here. The word "current" may make sense when used in context of an iterator, but much less so when used in the context of an exception. With other stateful systems, current to me implies "current state". It's very dependent on context, while also being "correct".

If you are willing to re-consider naming, I can think of 2 different ways of improving things:

1. Remove `CurrentAwareInterface`, make an `IterationAwareInterface` with `getIteration(): IterationAwareInterface`, and have `IteratorInterface` and `IterationExceptionInterface` extend it.
2. Incorporate [state machine](https://github.com/Dhii/machine-state-machine-interface) interfaces into this package.

Of course, these are just suggestions. I think "current" is still valid; merely mentioning the above in case it interests you.

**Comment by XedinUnknown** [comment]
Agreed. Point 1 done. Point 2 can be done by the implementation, if it wants. SoC has been restored.

**Pull request merged**
